[project]
name = "classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "mariadb>=1.1.12",
    "pandas>=2.3.0",
    "python-dotenv>=1.1.0",
    "sqlalchemy>=2.0.41",
]

[tool.uv.sources]
classification = { workspace = true }
